# Generated by Django 2.1.7 on 2019-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoterid', '0008_auto_20190316_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_p',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_p',
            field=models.FileField(upload_to=''),
        ),
    ]
